name: Deploy Artifact

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy:
    uses: valitydev/base-workflow/.github/workflows/maven-thrift-deploy.yml@5887af1d77791c8be93981b10f36a6f9d35fc630
    with:
      server-username: ${{ secrets.OSSRH_USERNAME }}
      server-password: ${{ secrets.OSSRH_TOKEN }}
      deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}