name: Erlang Build And Verify

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: valitydev/base-workflow/.github/workflows/erlang-thrift-build.yml@5887af1d77791c8be93981b10f36a6f9d35fc630